# Generated by Django 5.1.4 on 2025-03-13 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expensecategory_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('edit', 'Düzenleme'), ('delete', 'Silme')], max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
