# Generated by Django 5.1.4 on 2025-03-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_employeedocument_employeetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeetask',
            old_name='due_date',
            new_name='assignment_date',
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('atanmadı', 'Atanmadı'), ('atanmış', 'Atanmış'), ('tamamlandı', 'Tamamlandı')], default='atanmadı', max_length=50),
        ),
    ]
