# Generated by Django 5.1.4 on 2025-03-13 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_complaint_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150, verbose_name='Marka')),
                ('model', models.CharField(max_length=150, verbose_name='Model')),
                ('chassis_no', models.CharField(max_length=100, unique=True, verbose_name='Şasi No')),
                ('maintenance_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bakım Fiyatı')),
                ('last_maintenance_date', models.DateField(verbose_name='Son Bakım Tarihi')),
                ('estimated_maintenance_date', models.DateField(verbose_name='Tahmini Bakım Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Temsilci')),
            ],
        ),
    ]
