from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.home, name='home'),
    path('admin-login/', views.AdminLoginView.as_view(), name='admin_login'),
    path('temsilci-login/', views.TemsilciLoginView.as_view(), name='temsilci_login'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('temsilci-panel/', views.temsilci_panel, name='temsilci_panel'),
    path('add-temsilci/', views.add_temsilci, name='add_temsilci'),
    path('temsilci-list/', views.list_temsilci, name='list_temsilci'),
    path('admin-logout/', views.admin_logout, name='admin_logout'),
    path('temsilci-logout/', views.temsilci_logout, name='temsilci_logout'),
    path('add-expense-category/', views.add_expense_category, name='add_expense_category'),
    path('list-expense-categories/', views.list_expense_categories, name='list_expense_categories'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('list-expenses-admin/', views.list_expenses_admin, name='list_expenses_admin'),
    path('list-expenses-rep/', views.list_expenses_rep, name='list_expenses_rep'),
    path('edit-expense-category/<int:category_id>/', views.edit_expense_category, name='edit_expense_category'),
    path('delete-expense-category/<int:category_id>/', views.delete_expense_category, name='delete_expense_category'),
    path('expense-category-logs/', views.expense_category_logs, name='expense_category_logs'),
    path('add-customer/', views.add_customer, name='add_customer'),
    path('list-customers-rep/', views.list_customers_rep, name='list_customers_rep'),
    path('list-customers-admin/', views.list_customers_admin, name='list_customers_admin'),
    path('add-subscription-type/', views.add_subscription_type, name='add_subscription_type'),
    path('list-subscription-types/', views.list_subscription_types, name='list_subscription_types'),
    path('add-subscription-duration/', views.add_subscription_duration, name='add_subscription_duration'),
    path('list-subscription-durations/', views.list_subscription_durations, name='list_subscription_durations'),
    path('add-payment-type/', views.add_payment_type, name='add_payment_type'),
    path('list-payment-types/', views.list_payment_types, name='list_payment_types'),
    path('pending-customers/', views.list_pending_customers, name='list_pending_customers'),
    path('edit-customer-agreement/<int:customer_id>/', views.edit_customer_agreement, name='edit_customer_agreement'),
    path('add-employee/', views.add_employee, name='add_employee'),
    path('list-employees-admin/', views.list_employees_admin, name='list_employees_admin'),
    path('assign-employee-task/<int:employee_id>/', views.assign_employee_task, name='assign_employee_task'),
    path('list-employees-for-rep/', views.list_employees_for_rep, name='list_employees_for_rep'),
    path('add-employee-document/<int:employee_id>/', views.add_employee_document, name='add_employee_document'),
    path('list-employee-documents/<int:employee_id>/', views.list_employee_documents, name='list_employee_documents'),
    path('list-employees-admin/', views.list_employees_admin, name='list_employees_admin'),
    path('admin-panel/view-employee-documents/<int:employee_id>/', views.admin_view_employee_documents, name='admin_view_employee_documents'),
    path('list-employee-tasks/', views.list_employee_tasks, name='list_employee_tasks'),
    path('update-employee-task/<int:task_id>/', views.update_employee_task, name='update_employee_task'),
    path('delete-employee-task/<int:task_id>/', views.delete_employee_task, name='delete_employee_task'),
    path('employee-task-logs/', views.list_employee_task_logs, name='list_employee_task_logs'),
    path('add-material/', views.add_material, name='add_material'),
    path('list-materials/', views.list_materials, name='list_materials'),
    path('update-material/<int:material_id>/', views.update_material, name='update_material'),
    path('delete-material/<int:material_id>/', views.delete_material, name='delete_material'),
    path('add-material-transaction/', views.add_material_transaction, name='add_material_transaction'),
    path('list-material-transactions-admin/', views.list_material_transactions_admin, name='list_material_transactions_admin'),
    path('list-material-transactions-rep/', views.list_material_transactions_for_rep, name='list_material_transactions_for_rep'),
    path('list-payments-admin/', views.list_payments_admin, name='list_payments_admin'),
    path('add-payment/', views.add_payment, name='add_payment'),
    path('list-payments-rep/', views.list_payments_rep, name='list_payments_rep'),
    path('change-subscription-status/<int:customer_id>/<str:new_status>/', views.change_subscription_status, name='change_subscription_status'),
    path('add-complaint/', views.add_complaint, name='add_complaint'),
    path('list-complaints-rep/', views.list_complaints_rep, name='list_complaints_rep'),
    path('list-complaints-admin/', views.list_complaints_admin, name='list_complaints_admin'),
    path('update-complaint/<int:complaint_id>/', views.update_complaint, name='update_complaint'),
    path('add-request/', views.add_request, name='add_request'),
    path('list-requests-rep/', views.list_requests_rep, name='list_requests_rep'),
    path('list-requests-admin/', views.list_requests_admin, name='list_requests_admin'),
    path('add-vehicle/', views.add_vehicle, name='add_vehicle'),
    path('list-vehicles-rep/', views.list_vehicles_rep, name='list_vehicles_rep'),
    path('list-vehicles-admin/', views.list_vehicles_admin, name='list_vehicles_admin'),
    path('add-subscription-extra/', views.add_subscription_extra, name='add_subscription_extra'),
    path('list-subscription-extras-rep/', views.list_subscription_extras_rep, name='list_subscription_extras_rep'),
    path('list-subscription-extras-admin/', views.list_subscription_extras_admin, name='list_subscription_extras_admin'),
    path('cancel-subscription-extra/<int:extra_id>/', views.cancel_subscription_extra, name='cancel_subscription_extra'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
